services:
  api:
    build:
      context: ./Api_Project/Api
      dockerfile: Dockerfile
    ports:
      - "8090:8090"  # API'nin dışa açılacağı port
    depends_on:
      - pgadmin
      - mongodb
      - postgres-db  # Veritabanları ile iletişim

  postgres-db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: checkdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 81
    ports:
      - "8081:81"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres-db

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      #- ./mongod.conf:/etc/mongod.conf
    #command: ["mongod", "--config", "/etc/mongod.conf"]

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  mongodb_data:
  pgadmin:
